language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install scipy
# command to run tests
script: "nosetests nonpyrametric/tests"