language: python
python:
  - "2.7_with_system_site_packages"
  - "3.3_with_system_site_packages"
  - "3.4_with_system_site_packages"
  - "3.5_with_system_site_packages"
# command to install dependencies
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install .
# command to run tests
script: "nosetests nonpyrametric/tests"